bootstrapvz/common/tasks/boot.py, bootstrapvz/providers/gce/__init__.py
Add UpdateInitramfs task which is needed for this to take effect.
Enable both tasks for GCE.
Console output before
=====================
[    1.877142] sd 0:0:1:0: [sda] Attached SCSI disk
[    1.880163] sd 0:0:1:0: Attached scsi generic sg0 type 0
[    2.684132] tsc: Refined TSC clocksource calibration: 2500.000 MHz
[    4.824081] floppy0: no floppy controllers found
[    5.103671] work still pending
Begin: Loading essential drivers ... done.
Begin: Running /scripts/init-premount ... done.
Begin: Mounting root file system ... Begin: Running /scripts/local-top ... done.
Begin: Running /scripts/local-premount ... done.
[    5.313107] EXT4-fs (sda1): mounted filesystem with ordered data mode. Opts: (null)
...
[    7.751955] alg: No test for crc32 (crc32-pclmul)
[   10.728078] floppy0: no …
=> Blacklist floppy module to speed up boot by several seconds.

bootstrapvz/plugins/minimize_size/tasks.py
After vmware-vdiskmanager runs, the image is left with a 600
permission. This commit fixes it by preserving the file permission
before the shrink operation.
=> Recover file permissions after shrink a vmdk image

bootstrapvz/providers/gce/__init__.py, bootstrapvz/providers/gce/assets/initramfs-tools/scripts/local-premount/gce-disable-growroot, bootstrapvz/providers/gce/tasks/__init__.py, bootstrapvz/providers/gce/tasks/initd.py
This is a temporary fix to work around a bug in Debian where growpart can destroy a disk >2TB since it updates the partition table incorrectly (i.e. it can shrink the partition under some circumstances.
This bug is described in more detail in this thread: https://lists.debian.org/debian-cloud/2014/10/msg00018.html
Once a fix has been submitted to Debian, this change can be reverted.
Quick summary of the change:
This change adds a file to initramfs in /etc/initramfs-tools/scripts/local-premount/ called gce-disable-growroot. This is a shell script that checks the size of the disk and if it's greater than 2TB, it touches the file /etc/disable-growroot on the disk. When growroot discovers that file, it will not attempt to resize the root partition.
=> Disable resize on disks larger than 2TB

bootstrapvz/plugins/ansible/__init__.py, bootstrapvz/plugins/ansible/manifest-schema.yml, bootstrapvz/plugins/ansible/tasks.py
I'll update the dev_Plugins section with the following info once this gets merged.
This plugin runs the supplied ansible playbook in the chrooted environment similar to the puppet plugin.
* `playbook`: the path to the playbook on the host OS. ex) `"/opt/playbooks/webserver.yml"`
* required
* `hosts`: If you have your playbook broken up into different plays, specify the hostnames of the plays you want to run on the resulting image. ex) `['webserver']`
* `extra_vars`: You can supply extra vars to the playbook here with the same syntax. ex) `'foo=bar'`
* `tags`: Limit what runs on the playbook by providing the tags for tasks you'd like to run as a comma separated string. ex) `'install,configure'`
* `skip_tags`: Same as `tags`, but excludes those tasks.
* `opt_flags`: While not recommended, …
=> Added an Ansible plugin, which runs a playbook on the chroot

bootstrapvz/base/manifest-schema.yml, bootstrapvz/common/tasks/apt.py
It controls whether to include the 'deb-src' lines in image's
source.list.
Currently they are always included. This patch changes this
behavior by not including them by default; the user must set
this new config to true in order to include them.
This saves a bit of bandwidth in default installations. Also,
the use of src packages is not so usual in ordinary installations.
=> Add the manifest "include-source-type" key for packages object

bootstrapvz/plugins/image_commands/README.md, bootstrapvz/plugins/image_commands/tasks.py
Documentation says about that, but it's not implemented like that.
If the command to be executed is an array with just one string, it's
likely the user passed the entire command inside the string.
Plus, they benefit from shell expansion of wildcards like '*'.
=> Execute entries with a single string as shell commands

bootstrapvz/plugins/ec2_launch/__init__.py, bootstrapvz/plugins/ec2_launch/manifest-schema.yml, bootstrapvz/plugins/ec2_launch/tasks.py
It adds the ability to automatically launch an EC2 instance
after AMI registration.
It has no mandatory configuration, only optional ones, like
instance type, security groups, etc. They should be documented in
later documentation patches.
=> New plugin: ec2_launch

bootstrapvz/plugins/ec2_launch/__init__.py, bootstrapvz/plugins/ec2_launch/manifest-schema.yml, bootstrapvz/plugins/ec2_launch/tasks.py
If all you want is to test an image or product and to achieve this
you need to generate several images a day, you will end up with
lots of AMI's and snapshots that have no use in the end of the day.
This commit adds the new boolean manifest option "deregister_ami"
that, if True, deletes the recently created AMI and snapshot. So, the
final result will be only the running instance, nothing else.
=> ec2_launch: Allow to deregister the AMI after launching image

bootstrapvz/plugins/apt_proxy/README.rst, bootstrapvz/plugins/apt_proxy/manifest-schema.yml, bootstrapvz/plugins/apt_proxy/tasks.py
Add username and password settings to the APT Proxy plugin so that
users who are behind an authenticating proxy can still use bootstrap-vz
without having to jump through hoops. If either the username or password
are not set, then no authentication is used.
=> Add authentication support to the apt proxy plugin

bootstrapvz/common/tasks/ssh.py, bootstrapvz/plugins/root_password/__init__.py
Jessie comes with root login disabled for passwords, however,
if the user is using this plugin, chances are high that they
need to login via SSH as root.
=> root_password: Enable SSH root login

bootstrapvz/providers/ec2/ebsvolume.py, bootstrapvz/providers/ec2/tasks/ami.py
They are faster and the default when using AWS EC2 console.
If you think this is too intrusive, we could add a config parameter to let the user choose the volume type he wants...
=> Use SSD volumes instead of magnetic

bootstrapvz/plugins/apt_proxy/tasks.py
It seems some Debian versions of apt-cacher-ng return error
code 406 instead of 404:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=762969
This is my case in Jessie, for example.
This patch considers both codes as "valid".
=> apt_proxy: Also consider http error code 406

bootstrapvz/providers/ec2/README.rst, bootstrapvz/providers/ec2/__init__.py
To control whether ec2 init scripts should be installed
on the image. Defaults to true, to keep current behaviour.
=> Ec2: Add the variable "install_init_scripts"

bootstrapvz/providers/ec2/tasks/packages.py
Otherwise, keep Debian's default isc-dhcp-client, it works fine
on EC2.
=> EC2: Only install dhcpcd on releases before jessie

bootstrapvz/providers/gce/tasks/apt.py
The result is that we leave a set of apt list files current as of the image build on the resulting image instead of no cache whatsoever.
=> Change the order we clean up the apt state for GCE images.

bootstrapvz/providers/azure/tasks/packages.py
- Use manifest.provider instead of manifest.system
- Add 'parted' package required for recent versions of Azure agent
=> Fix for issue #231 + added 'parted' package

bootstrapvz/common/assets/init.d/expand-root
blkid output changed between wheezy and jessie breaking this script
=> Fix expand-root script to work for Debian 8 and simplify how partition types are formulated.

bootstrapvz/providers/azure/__init__.py, bootstrapvz/providers/azure/assets/udev.diff, bootstrapvz/providers/azure/tasks/__init__.py, bootstrapvz/providers/azure/tasks/udev.py
Hello guys, I would like to add a step to fix a boot delay issue with Azure. The `udev` init script is causing a delay when used with the recommended boot settings in Azure. (you have a link to the issue in the comments)
Feedback appreciated about the approach I took (applying a diff file instead of packing the complete file) -- overkill?
Thanks!
=> Patch udev init script to fix ROOTDELAY boot issue

CHANGELOG.rst, bootstrapvz/base/manifest-schema.yml, bootstrapvz/providers/ec2/tasks/network.py, manifests/official/ec2/ebs-jessie-amd64-hvm.yml
This PR makes the following three changes:
* Fix an error that is triggered when the kernel version installed into the image is different from the kernel version that's currently running. This happens when, for example, building a Debian Jessie image with Linux kernel 3.16.0-4-amd64 from within Ubuntu 14.04 running kernel 3.13.0-55-generic. Without this fix you'd get the following error:
```
Error! Your kernel headers for kernel 3.13.0-55-generic cannot be found.
Please install the linux-headers-3.13.0-55-generic package,
or use the --kernelsourcedir option to tell DKMS where it's located
Command 'chroot /target/ce7efc8d/root dkms build -m ixgbevf -v 2.16.1' returned non-zero exit status 1
Traceback (most recent call last):
File "/home/ubuntu/bootstrap-vz/bootstrapvz/base/main.py", line …
```
=> Fix DKMS version error; add Jessie & Btrfs support

bootstrapvz/plugins/vagrant/assets/box.ovf
While evaluating bootstrap-vz for creating official debian base boxes., I stumbled on this:
Vagrant documentation recommends to use 512MB for base boxes:
http://docs.vagrantup.com/v2/boxes/base.html
=> Set Virtualbox memory to 512 MB

bootstrapvz/providers/gce/assets/initramfs-tools/scripts/local-premount/gce-disable-growroot
This change makes two fixes. First, it fixes a race condition on Debian
8 GCE instances which caused instances with >2TB disks to fail. Second,
it adds the required "PREREQ" header to the script, which was previously
missing and caused errors at build time. These two issues are somewhat
unrelated to each other, but debugging the first led to finding the
second.
=> Fix a problem with Debian 8 on GCE with >2TB disks

bootstrapvz/common/tasks/grub.py
This changes GRUB_HIDDEN_TIMEOUT to 0 from true and sets
GRUB_HIDDEN_TIMEOUT_QUIET to true.
=> GRUB_HIDDEN_TIMEOUT should be a numeric value.

bootstrapvz/providers/ec2/assets/ec2/ec2net-functions
I was investigating issue with 30 second delay during boot time and found that it happens in a `networking` service:
```
systemd-analyze  blame 
30.188s networking.service
```
after some debugging I added one more exclusion for loopback interface and it takes 10 times less now:
```
systemd-analyze  blame 
3.078s networking.service
```
=> ignore loopback interface in udev rules

bootstrapvz/base/manifest-schema.yml, bootstrapvz/providers/kvm/manifest-schema.yml, bootstrapvz/providers/kvm/tasks/packages-kernels.yml, manifests/examples/kvm/jessie-arm64-virtio.yml
These minor changes allow bootstrap-vz to build a kvm image for jessie on arm64, by updating the schema to accept arm64 as an architecture, no bootloader, and providing an example manifest.
=> enable support for creating kvm images for jessie on arm64

bootstrapvz/common/assets/init.d/expand-root, bootstrapvz/common/tasks/initd.py, bootstrapvz/providers/ec2/__init__.py, bootstrapvz/providers/ec2/assets/bin/growpart, bootstrapvz/providers/ec2/tasks/packages.py, tests/integration/manifests/__init__.py
This continues the work started in #239 (addressing PR comments) and addresses #237 
Description from original PR:
> The script "growpart" was added as an asset, because
Debian's Jessie version (inside cloud-utils) package is
outdated and buggy.
> Then "expand-root" init script was modified to call growpart
before calling resize2fs. In fact, calling resize2fs without
resizing the partition first is useless.
> The task was named 'AddWorkaroundGrowpart' because it must
go away in the future in favor of using recent stuff in cloud-utils.
> Currently even the official images suffer this issue, that makes
the system use only 8 GiB, even if the user chooses a bigger
storage size inside AWS.
=> EC2: Added growpart script extension

README.rst
Hi, seems like euca2ools has a missing dependency. Please let me know if you could merge this. Thanks!
=> euca2ools requires libxslt which requires zlibg1-dev to build via pip.

bootstrapvz/plugins/admin_user/README.rst, bootstrapvz/plugins/admin_user/__init__.py, bootstrapvz/plugins/admin_user/manifest-schema.yml, bootstrapvz/plugins/admin_user/tasks.py
This commit adds authentication optionally with passwords or static
ssh pubkeys for the admin user.
There are now three ways to grant access to the admin user:
-  Set a password for the user, or
-  Provide a ssh public key to allow remote ssh login, or
-  Use the EC2 public key (EC2 machines only)
If a password is provided, this plugin sets the admin password. This
also re-enables password login (off by default in Jessie).
If the optional argument pubkey is present (it should be a full path
to a ssh public key), it will ensure that the ssh public key is used
to set up password less remote login for the admin user.
Only one of these options (password, or pubkey) may be specified.
If neither the password not a ssh public key location are specified,
and if the EC2 init scripts are installed, …
=> [admin_user]: Added support for password and static pubkey auth

bootstrapvz/common/task_groups.py, bootstrapvz/common/tasks/locale.py
Starting in version 2016a-1 (circa Jan 2016) the package tzdata
changed /etc/timezone into a symlink. This change is in unstable,
testing, and will be in the next release (stretch). This commit checks
the release, and creates a task to either copy the contents of the
zoneinfo file (jessie and older) or create a symbolic link (newer than
jessie).
Signed-off-by: Manoj Srivastava <srivasta@golden-gryphon.com>
=> [set localtime]: Set /etc/localtime by either copying or symlinking

CHANGELOG.rst, bootstrapvz/base/manifest-schema.yml, bootstrapvz/plugins/debconf/README.rst, bootstrapvz/plugins/debconf/__init__.py, bootstrapvz/plugins/debconf/schema.yaml, bootstrapvz/plugins/debconf/tasks.py
This is my take on #282.
This lets you set debconf answers before extra packages are installed (but after the OS setup).
=> Add a debconf plugin

bootstrapvz/providers/gce/tasks/packages-kernels.yml, bootstrapvz/providers/gce/tasks/packages.py, manifests/official/gce/jessie-backports.yml, manifests/official/gce/jessie.yml, manifests/official/gce/wheezy-backports.yml, manifests/official/gce/wheezy.yml
These packages were being added outside of bootstrap-vz by our build scripts.
Remove i386 kernels that GCE does not support as well as squeeze (never supported), and add in a stretch kernel.
=> Cleanup package list and add in other packages

bootstrapvz/plugins/admin_user/__init__.py
Currently, `admin_user` attempts to add the task `AdminUserPublicKeyEC2` if no pubkey is specified, which results in an error if the provider is not EC2.
This patch introduces an additional check, and simply sets no public key if none is defined and the provider is not EC2.
=> admin_user plugin: Fix non-EC2 behaviour

bootstrapvz/plugins/file_copy/README.rst, bootstrapvz/plugins/file_copy/__init__.py, bootstrapvz/plugins/file_copy/manifest-schema.yml, bootstrapvz/plugins/file_copy/tasks.py
The manifest for the `file_copy` plugin was failing to validate the data properly.
=> file_copy: Fix manifest and document

bootstrapvz/base/manifest.py, bootstrapvz/base/metaschema.json
This modifies `manifest.schema_validator` (which is passed as argument to all the `validate_schema` functions) to:
- first validate the schema against the JSON metaschema;
- then validate the manifest against the schema.
This is probably suboptimal, as the metaschema is reloaded every time, but I noticed no significant impact.
=> manifest: Validate schemata before use

bootstrapvz/providers/gce/__init__.py, bootstrapvz/providers/gce/tasks/initd.py
The volume is not /dev/loop0 but it should be /dev/sda.
Outside the scope of fixing my immediate problem here, should there be something in the manifest for volume to denote the resulting image's device_path instead of the install device_path (which will change depending upon what kind of volume you are using). If you agree, I'll create an issue for that because it seems like something you should be able to specify in a manifest file.
=> Again fix the expand-root script for GCE.

bootstrapvz/providers/gce/README.rst, bootstrapvz/providers/kvm/README.rst, bootstrapvz/providers/virtualbox/README.rst
Fix invalid item levels.
All manifest settings should be same toctree level like following.
- EC2
- Manifest settings
- Google Compute Engine
- Manifest settings
- KVM
- Manifest settings
=> fix document toctree

bootstrapvz/base/__init__.py, bootstrapvz/base/manifest-schema.yml, bootstrapvz/common/task_groups.py, bootstrapvz/common/tasks/apt.py, manifests/README.rst
This adds the possibility of adding configuration snippets in `apt.conf` and `apt.conf.d`:
```yaml
packages:
apt.conf.d:
00InstallRecommends:  >-
APT::Install-Recommends "false";
APT::Install-Suggests   "false";
```
Those settings are applied before packages get installed, making it viable to set things like `APT::Install-Recommends` or `Acquire::http::Proxy`.
Moreover, 2 fixup commits are included.
=> Enable setting `apt.conf(5)` options

bootstrapvz/providers/gce/tasks/packages.py
busybox as a dependency seems to have disappeared at some point in recent PR's and is required for initrd with the growroot disable script that currently exists in GCE images.
=> Add busybox as a required package for GCE.

bootstrapvz/providers/gce/tasks/host.py
An environment with AF_INET6 sockets but no loopback interface creates
nothing but pain.
If an IPv4 server binds to `0.0.0.0:8080`, clients may connect to
`0.0.0.0:8080`, which automatically picks `127.0.0.1` as a source address.
However, when a server binds to `[::]:8080`, the absence of `::1` causes
clients to fail with `ENETUNREACH`.
For a demonstration, run the following in a python shell:
```
import socket
s = socket.socket(socket.AF_INET6, socket.SOCK_STREAM, 0)
s.bind(("", 0))
print s.getsockname()  # Example: ('::', 39079, 0, 0)
s.listen(10)
c = socket.socket(socket.AF_INET6, socket.SOCK_STREAM, 0)
c.connect(s.getsockname())
print c.getsockname(), c.getpeername()
```
This yields the following error:
```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File …
```
=> Do not remove ::1 from the loopback interface.

bootstrapvz/plugins/cloud_init/__init__.py
AdjustGrowpartWorkaround modifies /etc/init.d/expand-root, which doesn't
exist if AddExpandRoot doesn't run.
=> cloud_init disable AdjustGrowpartWorkaround

bootstrapvz/providers/gce/__init__.py
We thought this was already set but it seems to have changed at some point in history (functionally in Debian configs of boostrap-vz).
https://cloud.google.com/compute/docs/instances/connecting-to-instance#root
=> Disable SSH root login on GCE images.

bootstrapvz/common/tasks/grub.py
This needed changing to hvc0 for ec2, and was accidentally changed
for all other providers.  Since the ec2 provider overrides to hvc0
anyway, we can just change this default to the setting that works
for everyone else.
Fixes: #318
=> Set a default of GRUB_CMDLINE_LINUX_DEFAULT="console=ttyS0"

bootstrapvz/plugins/cloud_init/README.rst, bootstrapvz/plugins/cloud_init/__init__.py, bootstrapvz/plugins/cloud_init/manifest-schema.yml, bootstrapvz/plugins/cloud_init/tasks.py
Very similar to user customization.
Use case is:
```
...
packages:
sources:
docker:
- deb http://apt.dockerproject.org/repo/ debian-jessie main
install:
- docker-engine
plugins:
cloud_init:
metadata_sources: Ec2
username: admin
groups:
- docker
```
`docker_daemon` requires Grub due to `EnableMemoryCgroup` and I prefer installing docker from .deb.
`commands` can't `usermod` because the user doesn't exist yet.
I ended up here.
=> cloud-init: modify groups

bootstrapvz/providers/gce/README.rst, bootstrapvz/providers/gce/tasks/image.py
GCE image upload simply didn't work.  With this PR, it does.  Changes:
* syntax is `gcloud compute images`, not `gcloud compute image`
* --source-uri=<uri> should be a single argument
* Expand the description template before passing it to gcloud
* Rename image in tar file to disk.raw
* Name the image as specified in the manifest
* Documentation improvements
=> Fixes for uploading a GCE image

bootstrapvz/providers/gce/__init__.py, bootstrapvz/providers/gce/tasks/apt.py, manifests/official/gce/README.rst, manifests/official/gce/jessie-minimal.yml, manifests/official/gce/jessie.yml
Fix missing source repo's in GCE images. Add back baseline apt cache as well. Add in additional GCE guest package into manifests (init files were split into their own package to make the python package adhere to pypi standards).
=> Fix some GCE image issues.

bootstrapvz/common/tasks/apt.py, bootstrapvz/plugins/file_copy/__init__.py, bootstrapvz/plugins/file_copy/tasks.py
- ~~admin_user: Allow designating pubkeys by relative path~~
- file_copy: Allow copying directories
- apt: Don't add a security mirror for obsolete releases  
This made the build of a squeeze image (for instance) fail.
=> Misc. fixes & improvements

bootstrapvz/providers/docker/tasks/image.py
The extra quoting breaks on some versions of Docker, such as the one available on Travis.
See <https://travis-ci.org/hashbang/docker-gitolite/builds/151947017#L527> for a build log.
=> docker: Fix quoting that breaks some versions of Docker

bootstrapvz/common/phases.py, bootstrapvz/common/task_groups.py, bootstrapvz/common/tasks/apt.py
This makes wrong (inexistent or malformed) trusted-keys
keyring fail the image build at validation-time, rather
than in the package installation phase.
=> apt: Validate packages.trusted-keys

bootstrapvz/common/tools.py, bootstrapvz/plugins/admin_user/__init__.py, bootstrapvz/plugins/admin_user/manifest-schema.yml, bootstrapvz/plugins/admin_user/tasks.py, bootstrapvz/plugins/file_copy/README.rst, bootstrapvz/plugins/file_copy/__init__.py, bootstrapvz/plugins/file_copy/tasks.py
This is a followup on #331, since this specific patch was dropped.
@andsens I agree that paths relative to the manifest would be best.
However, while implementing this I ran into trouble: there is no way for `validate_manifest` to access `manifest.path`.
Moreover, the `file_copy` plugin also allows relative paths, and has the same issue (pathes end up being relative to the working directory).
I suggest that we pass the entire `manifest` object to `validate_manifest`, rather than `manifest.data`, `manifest.schema_validator` and `manifest.validation_error`.
=> admin_user & file_copy: Make paths relative to the manifest

bootstrapvz/base/manifest-schema.yml, bootstrapvz/base/manifest.py, bootstrapvz/providers/ec2/__init__.py, bootstrapvz/providers/ec2/manifest-schema.yml, bootstrapvz/providers/ec2/tasks/ami.py, manifests/official/ec2/ebs-stretch-amd64-hvm.yml
- fully implemented for EC2 provider only, other providers will require
validation and applying to the instances added
- brand new Stretch manifest with top level AMI tags
- some minor Jessie manifest editorials
- some minor yaml schema editorials
=> Added tagging for the created images +

bootstrapvz/providers/ec2/tasks/network.py
enhanced network instances, it's being activated as default in GCC6 for
Stretch upwards.
=> Disabling PIE during ixgbevf compilation for AWS +

bootstrapvz/plugins/ec2_publish/manifest-schema.yml, bootstrapvz/providers/ec2/manifest-schema-s3.yml, bootstrapvz/providers/ec2/tasks/ami-akis.yml
https://aws.amazon.com/about-aws/whats-new/2016/12/announcing-the-aws-canada-central-region/ 🇨🇦 !
This may not be usable yet: `aws ec2 describe-images --owners amazon --filters Name=name,Values=pv-grub-*.gz --region ca-central-1` doesn't output an i386 kernel.
=> Support ca-central-1

bootstrapvz/providers/ec2/tasks/network.py
The URL for the `ixgbevf` driver is currently returning a 404. Updating
to the new mirror URL gets EC2 builds with enhanced networking support
working again.
=> EC2: Update the URL to dowload the ixgbevf driver

bootstrapvz/plugins/admin_user/tasks.py
In the current state, if you were to specify a pubkey under the admin_user plugin, bootstrap fails with the following error:
```
Generating tasklist
Adding commands required for formatting
Adding commands required for partitioning the volume
Check that the public key is a valid file
[Errno 2] No such file or directory
Traceback (most recent call last):
File "/root/bootstrap-vz/bootstrapvz/base/main.py", line 111, in run
tasklist.run(info=bootstrap_info, dry_run=dry_run)
File "/root/bootstrap-vz/bootstrapvz/base/tasklist.py", line 44, in run
task.run(info)
File "/root/bootstrap-vz/bootstrapvz/plugins/admin_user/tasks.py", line 26, in run
ret, _, stderr = log_call('/usr/bin/ssh-keygen -l -f ' + abs_pubkey)
File "/root/bootstrap-vz/bootstrapvz/common/tools.py", line 33, in log_call …
```
=> Fix subprocess call to verify admin_user public key

bootstrapvz/plugins/expand_root/tasks.py
For whatever reason, there was an ordering issue where this class was being run before anything else and failing because there wasn't a jessie-backports sources list yet (not to mention a filesytem at all). Moving this to the package_installation phase fixes the problem.
=> Fix an ordering issue with the expand-root plugin.

CHANGELOG.rst, CONTRIBUTING.rst, bootstrapvz/plugins/admin_user/README.rst, bootstrapvz/plugins/expand_root/README.rst, bootstrapvz/plugins/google_cloud_repo/README.rst, bootstrapvz/remote/README.rst, manifests/README.rst
I have found some typos and layout inconsistencies in the documentation. This is a pull request with fixes for your consideration.
=> fix some typos in documentation

bootstrapvz/providers/gce/tasks/boot.py
Note this feature will only work in kernels >3.19 and is only relevant in GCE. I can't speak to other platforms as this is a virtual device level feature.
=> Enable SCSI block multiqueue for GCE Stretch images.

bootstrapvz/common/fs/loopbackvolume.py
Removes undeleted loopdevice partitions created by kpartx.
This was needed as "bootstrap-vz tries very hard to clean up after itself " and because LVM tries to read from these files and gives off warnings.
Since Util-linux 2.21, losetup is able to scan the partition table of the newly created loop device. Therefore it is able to unmap them as well. By adding a --partscan, losetup tries to map the partitions when the loop device is mounted, and will unmap them when it is detached.
=> Fix loopdevice partitions not being unmapped correctly

bootstrapvz/base/fs/__init__.py, bootstrapvz/base/manifest-schema.yml, bootstrapvz/common/fs/logicalvolume.py, bootstrapvz/common/tasks/logicalvolume.py, bootstrapvz/providers/kvm/README.rst, bootstrapvz/providers/kvm/__init__.py, bootstrapvz/providers/kvm/manifest-schema.yml, manifests/examples/kvm/jessie-lvm.yml
Enables the use of Logical Volumes as disk backends.
This was needed as we store our VMs through LVM and wanted to build 
the image directly onto a lv.
It uses an existing volume group and has no support for creating a new one.
It will not override an existing logical volume and fail gracefully.
The lv is created, activated and then mounted as a loop device.
The boostraping process is then launched on the loop device.
Once the process is completed, the lv is unmounted and desactivated.
The created lv will be deleted should the boostraping process fail.
The lv must be activated before use.
A manifest has been included for testing purposes.
=> Add LVM as a disk backend

bootstrapvz/base/fs/__init__.py, bootstrapvz/common/fs/qcow2volume.py, bootstrapvz/providers/kvm/README.rst, bootstrapvz/providers/kvm/manifest-schema.yml, manifests/README.rst, manifests/examples/kvm/jessie-qcow2.yml
This enables building an image with qcow2 as a disk backend.
Qcow2 is only supported by KVM.
The update implements a new class that inherits from QEMUVolume and just
needs the extension and file format.
A manifest has been included for testing purposes.
=> Add qcow2 as a disk backend for KVM

bootstrapvz/plugins/minimize_size/__init__.py
The `filter_tasks` variable is only used in the `if 'dpkg'` branch, but curiously it is only initialized in the `if 'apt'` branch.
=> Fix lone minimize_size/dpkg without apt

bootstrapvz/plugins/minimize_size/tasks/mounts.py
I am getting the following errors when using the `minimize_size` plugin:
```
[…]
Mounting folders for writing temporary and cache data
Writing aptitude sources to disk
Generating system locale
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
LANGUAGE = (unset),
LC_ALL = (unset),
LANG = "pl_PL.utf8"
are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
Disabling daemon autostart
Updating the package cache
W: GPG error: http://security.debian.org stretch/updates InRelease: Couldn't create temporary file /tmp/apt.conf.kQin5D for passing config to apt-key
W: The repository 'http://security.debian.org stretch/updates InRelease' is not signed.
W: GPG error: http://deb.debian.org/debian stretch-updates …
```
=> minimize_size: make sure the permissions of bindmounts are preserved

bootstrapvz/common/tasks/host.py
On Unix, with `shell=True`, the shell default to /bin/sh.
Using `Popen(['type', command], shell=True)` is equivalent to calling
`Popen(['/bin/sh', '-c', 'type', command])`.
In this case `'command'` becomes a positional parameter to the shell,
and not an argument to the command `'type'`.
One solution would be to pass a single string as parameter.
The problem is that with `shell=True`, we wouldn't be safe from a shell injection,
so it is wiser to use a python only solution.
The package distutils is part of the standard distribution, so it doesn't add
extra dependencies.
The method find_executable has the same behaviour as 'which' on bash, it 
will return the path to the executable or `None` if it was not found.
Logging needs to be added as it was previously handled by log_check_call().
This …
=> Fix unfailing CheckExternalCommands

bootstrapvz/plugins/puppet/tasks.py
* fixed an issue where apt sources get written before the 
InstallPuppetlabsPC1ReleaseKey task is performed. added a successor
to the task.
* tox is green
=> Puppet tasks fix commit

manifests/official/gce/README.rst, manifests/official/gce/jessie-minimal.yml, manifests/official/gce/jessie.yml, manifests/official/gce/stretch-minimal.yml, manifests/official/gce/stretch.yml
GCE packages are now Debian policy compliant and therefore we have new package names and repositories.
=> Update Google Compute Engine package and repository structure.

bootstrapvz/providers/ec2/tasks/ami.py
Allow empty names for existing AMIs
=> Don’t crash on empty AMI name

bootstrapvz/providers/ec2/tasks/network.py
Apply new version when release is stretch or higher.
=> #397 fix: Installing networking kernel driver using DKMS fails in stretch

bootstrapvz/plugins/commands/README.rst
Commands passed to the commands plugin are not chrooted in the image.
Therefore the given example is misleading as it will remove the locales on the host and not on the image.
The use of `chroot {root}` should be advised.
=> Update misleading documentation

bootstrapvz/common/task_groups.py
Currently if the variant minbase is used, the network task is skipped. But if the netbase package is installed, the network should be configured.
=> allow networking task when netbase pkg is present

bootstrapvz/plugins/root_password/README.rst, bootstrapvz/plugins/root_password/manifest-schema.yml, bootstrapvz/plugins/root_password/tasks.py, manifests/examples/virtualbox/stretch-vagrant.yml
Added an option to the root_password plugin to use a password hash.
- Added password-crypted to root_password plugin.
- Updated the docs for root_password plugin
- Added password-crypted to example manifest for stretch vagrant
=> Add password-crypt to root password plugin

bootstrapvz/providers/ec2/tasks/network.py
current url is a 404
there is also https://downloadmirror.intel.com/18700/eng/ixgbevf-4.3.2.tar.gz
=> update intel ixgbevf url

bootstrapvz/common/assets/init.d/jessie/generate-ssh-hostkeys, bootstrapvz/common/assets/init.d/wheezy/generate-ssh-hostkeys, bootstrapvz/common/tasks/ssh.py
ED25519 ssh host key pair is not removed from ```/etc/ssh```:
```
$ ls -l /etc/ssh/ssh_host_*
-rw------- 1 root root 399 Jan  8 16:39 etc/ssh/ssh_host_ed25519_key
-rw-r--r-- 1 root root  94 Jan  8 16:39 etc/ssh/ssh_host_ed25519_key.pub
```
ED25519 ssh key pair is created since OpenSSH 6.5 (6.7 in Debian jessie) https://wiki.debian.org/SSH#Installation_of_the_server
=> Remove ED25519 ssh host key pair from image

bootstrapvz/common/tasks/grub.py
Minor changes to GRUB configuration regarding virtual and serial consoles:
* Corrected GRUB key/variable.
* Print kernel log messages that precede the initialisation of the traditional console to a serial console.
* Add console settings to both - default and recovery GRUB options (```GRUB_CMDLINE_LINUX``` instead of ```GRUB_CMDLINE_LINUX_DEFAULT```).
Above changes do not influence GRUB configuration modifications made by providers (Azure, GCE, EC2, VirtualBox).
GRUB documentation https://www.gnu.org/software/grub/manual/grub/grub.html#Simple-configuration 
Kernel documentation https://github.com/torvalds/linux/blob/master/Documentation/admin-guide/serial-console.rst
=> Minor changes to GRUB configuration regarding console and serial console

bootstrapvz/plugins/tmpfs_workspace/README.rst, bootstrapvz/plugins/tmpfs_workspace/__init__.py, bootstrapvz/plugins/tmpfs_workspace/tasks.py
A proof-of-concept with no documentation yet, for discussion.
I noticed that a full image build for one of my images takes about an hour on my home server with no SSD, but more than enough RAM. Tried mounting `tmpfs` over the workspace directory, and I started getting builds in 3 minutes. The idea sounds generic enough for other people to also benefit, so I wrote a plugin.
I should probably split the `MountTmpfs` task into two, to allow proper clean-up if `makedirs` succeeds, but `mount` fails.
I'd prefer not having an additional directory for `CreateWorkspace` to run, but I didn't find any good way to do so. I cannot replace/delete `CreateWorkspace` from a plugin. My first thought was to make `MountTmpfs` run after `CreateWorkspace` and simply mount `tmpfs` over the directory created by …
=> tmpfs_workspace: Plugin for having workspace on tmpfs for speed

.yamllint, manifests/examples/azure/jessie.yml, manifests/examples/azure/wheezy.yml, manifests/examples/ec2/ebs-unstable-amd64-pvm-contrib.yml, manifests/examples/kvm/jessie-arm64-virtio.yml, manifests/examples/kvm/jessie-puppet.yaml, manifests/examples/kvm/jessie-virtio.yml, manifests/examples/kvm/stretch-puppet.yaml, manifests/examples/kvm/stretch-virtio-partitions.yml, manifests/examples/kvm/wheezy-virtio.yml, manifests/official/ec2/s3-wheezy-amd64-pvm-cn-north-1.yml, manifests/official/gce/buster-minimal.yml, manifests/official/gce/buster.yml, manifests/official/gce/deprecated/wheezy-backports.yml, manifests/official/gce/deprecated/wheezy.yml, manifests/official/gce/jessie-minimal.yml, manifests/official/gce/jessie.yml, manifests/official/gce/stretch-minimal.yml, manifests/official/gce/stretch.yml, tox.ini
Add http://yamllint.readthedocs.io/ linter to check manifests files. 
I added yamllint environment to tox right after invoking flake8.
One nonadherence from default yamllint rules (```.yamllint```) is line length - changed from 80 to 160 characters. It's because lines that violate this rule are URLs and release names and I don't see a point in making it more complicated than it should be.
=> Add yamllint linter to check manifests files

bootstrapvz/providers/virtualbox/tasks/boot.py
Force order of tasks that add console=xxx to kernel command line (VirtualBox), as we discussed in https://github.com/andsens/bootstrap-vz/pull/436#issuecomment-359170266.
=> Force order of tasks that add console=xxx to kernel command line (VirtualBox)

bootstrapvz/plugins/minimize_size/README.rst, bootstrapvz/plugins/minimize_size/__init__.py
qemu-img also supports raw and qcow2 formats, so let's allow shrinking them too.
```
$ qemu-img --help | grep ^Supported
Supported formats: blkdebug blkreplay blkverify bochs cloop dmg file ftp ftps gluster host_cdrom host_device http https iscsi iser luks nbd nfs null-aio null-co parallels qcow qcow2 qed quorum raw rbd replication sheepdog ssh vdi vhdx vmdk vpc vvfat
```
=> qemu-img also supports shrinking raw and qcow2 formats

bootstrapvz/providers/ec2/README.rst, bootstrapvz/providers/ec2/manifest-schema.yml, bootstrapvz/providers/ec2/tasks/network.py
Add ability to declare version of the Amazon driver for EC2 instances. Currently, bootstrap-vz is pulling from master, but the version is incorrectly labeled at `1.0.0`.
I need to add docs, but I wanted feedback first.
=> select version for amzn-driver

manifests/examples/docker/jessie-minimized.yml
The new line at the end of the description value was breaking "Creating docker image"
=> Fix example docker manifest

bootstrapvz/base/manifest-schema.yml, bootstrapvz/common/tasks/bootstrap.py, manifests/README.rst
Exposing GPG flags for debootstrap:
- `--keyring=K`
- `--no-check-gpg`
- `--force-check-gpg`
=> Expose gpg flags for debootstrap

bootstrapvz/plugins/minimize_size/__init__.py, bootstrapvz/plugins/minimize_size/manifest-schema.yml, bootstrapvz/plugins/minimize_size/tasks/shrink.py, manifests/examples/kvm/stretch-cloudimg.yml
Add new shrink type to the minimize_size plugin, `qemu-img-no-compression`, to add the ability to create non-compressed QCOWs
=> Ability to create non-compressed QCOW

manifests/examples/kvm/jessie-arm64-virtio.yml, manifests/examples/kvm/jessie-puppet.yaml, manifests/examples/kvm/jessie-virtio.yml, manifests/examples/kvm/stretch-console.yml, manifests/examples/kvm/stretch-puppet.yaml, manifests/examples/kvm/stretch-virtio-partitions.yml, manifests/examples/kvm/wheezy-virtio.yml
Fix example manifest for the virtio modules, virtio_modules -> virtio
=> Correct virtio param in example manifests

bootstrapvz/common/tasks/dpkg.py, bootstrapvz/plugins/minimize_size/__init__.py, bootstrapvz/plugins/minimize_size/tasks/dpkg.py, bootstrapvz/providers/docker/README.rst, bootstrapvz/providers/docker/__init__.py, bootstrapvz/providers/docker/assets/docker-apt-speedup, bootstrapvz/providers/docker/tasks/__init__.py, bootstrapvz/providers/docker/tasks/settings.py, manifests/examples/docker/stretch-minimized.yml, manifests/examples/docker/stretch.yml
From https://github.com/moby/moby/blob/e2e5d4bc9da5ba17bb2822909611f8300fdd80f0/contrib/mkimage/debootstrap,
- setting dpkg unsafe-io
- allowing kernel autoremove
=> Add Docker specific settings

bootstrapvz/common/tasks/apt.py
Set permission on trusted.gpg file to 644 to address:
`The key(s) in the keyring /etc/apt/trusted.gpg.d/* are ignored as the file is not readable by user '_apt' executing apt-key.`
=> set permissions for apt gpg pub keys

bootstrapvz/base/fs/partitions/base.py
Some build environments (e.g. Google Cloud Container Builder docker
images) don't have enough of a /dev filesystem to have
/dev/disk/by-uuid/ by default. Make them if they don't exist.
=> Create device dirs if they do not exist

bootstrapvz/providers/ec2/README.rst, bootstrapvz/providers/ec2/ebsvolume.py, bootstrapvz/providers/ec2/tasks/ebs.py
Add tags also to the EBS volume when it is created. The tags can be used to set more specific IAM policies that limit operations on the volumes.
The same tags are already set for ebs snapshots and AMIs.
=> Tag ebs volumes when using ec2 provider

bootstrapvz/common/tools.py, bootstrapvz/plugins/cloud_init/tasks.py, bootstrapvz/plugins/ntp/tasks.py
Commit 701678c9 changes print statements to print functions with end=' '. As the printed strings contain newlines, this causes a space to be written as the first character of the following line causing them to be indented.
An example config that is broken. Here disabling modules indents all the other lines of cloud.cfg except the first one causing the username name setting to fail as it expects indenting to be certain number of spaces.
```
plugins:
cloud_init:
metadata_sources: Ec2
username: admin
disable_modules:
- locale
- mounts
```
This commit removes the spaces by specifying end=''.
=> Fix cloud-init setup broken by pylint changes

bootstrapvz/providers/ec2/README.rst, bootstrapvz/providers/ec2/__init__.py, bootstrapvz/providers/ec2/ebsvolume.py, bootstrapvz/providers/ec2/manifest-schema.yml, bootstrapvz/providers/ec2/tasks/ebs.py
This adds support for using encrypted EBS volume with EC2 provider. The resulting snapshot and AMI are encrypted and they can be used to launch EC2 instances with encrypted root volume. Custom KMS key can be used by specifying kms_key_id or otherwise the default kms key is used.
More information about AMI encryption:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AMIEncryption.html
Closes #405 
This pull request conflicts with https://github.com/andsens/bootstrap-vz/pull/446 that I can update if this is merged first.
=> Add support for encrypted AMIs

bootstrapvz/plugins/puppet/tasks.py, bootstrapvz/providers/ec2/tasks/boot.py
In each of these cases we have an un-escaped \n or \t that
gets passed to a regex.  That means that the regexes actually
contain tabs or newlines, respectively.  After this change
an actual '\t' and '\n' are passed in instead.
I have not tested this!  I am writing this patch based on
the assumption that /surely/ the original authors meant
to pass in \t and \n to the regex and not actual tab
or newline characters.
=> Fix a couple of (presumed) issues with regex escaping.
