bootstrapvz/common/task_groups.py, bootstrapvz/common/tasks/boot.py
So that we are able to see the System Log through EC2 console
or command line tools.
=> Don't boot quietly on extlinux (aws)

bootstrapvz/common/tasks/ssh.py
fix issue https://github.com/andsens/bootstrap-vz/issues/218
=> fix ^PermitRootLogin regex

bootstrapvz/providers/gce/tasks/packages.py
After spending some additional time troubleshooting, this seems to be a better way to solve the issue that I was having with local packages defined in the manifest.
=> Install GCE packages before Manifest packages.

manifests/examples/azure/jessie.yml, manifests/examples/azure/wheezy.yml
Quick example manifest for Jessie on Azure
=> Azure Jessie example manifest

bootstrapvz/providers/virtualbox/README.rst, manifests/examples/virtualbox/wheezy-vagrant.yml, manifests/examples/virtualbox/wheezy.yml
iso is provided by virtualbox-guest-additions-iso deb
=> Vbox guest additions iso path fix

setup.py
=> Excluding docs from binary package

bootstrapvz/providers/gce/tasks/apt.py, bootstrapvz/providers/gce/tasks/image.py
Change gcutil command to gcloud as gcutil is deprecated.
=> Change location of GCE apt repo's (this is an interim change).

bootstrapvz/providers/ec2/manifest-schema.yml
omission from c880a6849a589197420c32ef59d754b9e37daa16 ?
=> Remove stale requirement

.travis.yml
This should help getting the builds started much faster.
=> Travis: use the container-based test environment

bootstrapvz/providers/ec2/tasks/connection.py
Fixes #259 
Trying to be minimally invasive.
=> AWS: support IAM role

bootstrapvz/plugins/file_copy/README.rst, bootstrapvz/providers/ec2/manifest-schema-s3.yml
Small improvement, reference @ http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html
=> ec2: sync regions in schema

CHANGELOG.rst, bootstrapvz/plugins/ec2_publish/README.rst, bootstrapvz/plugins/ec2_publish/__init__.py, bootstrapvz/plugins/ec2_publish/manifest-schema.yml, bootstrapvz/plugins/ec2_publish/tasks.py
=> ec2_publish plugin

bootstrapvz/common/phases.py, bootstrapvz/common/tasks/bootstrap.py, bootstrapvz/common/tasks/filesystem.py, bootstrapvz/common/tasks/host.py, bootstrapvz/common/tasks/loopback.py, bootstrapvz/common/tasks/partitioning.py, bootstrapvz/plugins/ansible/tasks.py, bootstrapvz/plugins/apt_proxy/tasks.py, bootstrapvz/plugins/chef/tasks.py, bootstrapvz/plugins/minimize_size/tasks/shrink.py, bootstrapvz/plugins/puppet/tasks.py, bootstrapvz/plugins/vagrant/tasks.py, bootstrapvz/providers/docker/tasks/commands.py, bootstrapvz/providers/ec2/tasks/host.py, bootstrapvz/providers/virtualbox/tasks/guest_additions.py
This moves existing tasks that only perform extended validation (file exists, server is reachable, ...) to the new `validation` phase.
=> Move checking tasks to the validation phase

bootstrapvz/plugins/ec2_launch/README.rst, bootstrapvz/plugins/ec2_launch/manifest-schema.yml, bootstrapvz/plugins/ec2_launch/tasks.py
* added ssh_key parameter to the manifest to connect with (have to be
present in AWS)
* added readme
* changed instance type to something what can run outside VPC (m3.medium)
=> Plugin: ec2_launch ssh key, instance type, etc. +

bootstrapvz/base/bootstrapinfo.py, manifests/README.rst, manifests/examples/azure/jessie.yml, manifests/examples/azure/wheezy.yml
Fixing andsens/bootstrap-vz#338
=> Switching from httpredir.debian.org to deb.debian.org

bootstrapvz/common/tasks/initd.py, bootstrapvz/common/tasks/ssh.py, bootstrapvz/plugins/cloud_init/manifest-schema.yml, bootstrapvz/providers/ec2/__init__.py
This set of patches allows to create Stretch AMI and should also be a good background for Stretch for other providers
=> Finishing touches for Stretch

bootstrapvz/common/tasks/apt.py, bootstrapvz/providers/gce/__init__.py, manifests/official/gce/README.rst, manifests/official/gce/stretch-minimal.yml, manifests/official/gce/stretch.yml
There are still some outstanding issues with the disk expansion scripts. I will look into those separately. For now I just disabled them.
=> Fixes to create stretch images. Add stretch manifest for GCE.

bootstrapvz/common/releases.py, bootstrapvz/common/tasks/apt.py, tests/unit/releases_tests.py
Stretch release to stable is June 17(tonight/tomorrow depending on time zone).
=> Promote stretch to stable, add buster as testing, jessie to oldstable.

bootstrapvz/common/tasks/network-configuration.yml, bootstrapvz/providers/gce/tasks/packages-kernels.yml, manifests/official/gce/README.rst, manifests/official/gce/buster-minimal.yml, manifests/official/gce/buster.yml
- And generally support buster for test builds.
=> Add GCE buster builds.

bootstrapvz/base/bootstrapinfo.py, bootstrapvz/base/manifest-schema.yml, bootstrapvz/common/tasks/apt.py, manifests/README.rst, manifests/examples/kvm/jessie-lvm.yml
Added a security mirror setting to packages.
=> Added security field to packages.

bootstrapvz/plugins/minimize_size/README.rst, bootstrapvz/plugins/minimize_size/__init__.py, bootstrapvz/plugins/minimize_size/manifest-schema.yml, bootstrapvz/plugins/minimize_size/tasks/shrink.py
I haven't actually tested this on vdi, but based on `qemu-img`'s documentation, it should work just as well.
=> minimize_size: New `repack` option for qemu-img-based repacking

bootstrapvz/common/task_groups.py, bootstrapvz/common/tasks/cleanup.py, bootstrapvz/providers/docker/__init__.py
Cleaning machine ID. Fixes #427
=> Cleaning machine ID

bootstrapvz/plugins/minimize_size/tasks/shrink.py
Maybe I'll remember this irregularity now…
=> minimize_size: Typo in temporary file name

bootstrapvz/plugins/minimize_size/tasks/shrink.py
Seems like one would want a compressed QCOW2 image if the volume is being shrunk.
=> Compress QCOW2 when shrinking

bootstrapvz/base/fs/partitionmaps/gpt.py, bootstrapvz/base/fs/partitionmaps/msdos.py, bootstrapvz/base/pkg/sourceslist.py, bootstrapvz/common/fsm_proxy.py, bootstrapvz/common/tasks/bootstrap.py, bootstrapvz/common/tasks/grub.py, bootstrapvz/common/tasks/host.py, bootstrapvz/common/tasks/logicalvolume.py, bootstrapvz/common/tasks/loopback.py, bootstrapvz/common/tools.py, bootstrapvz/plugins/cloud_init/__init__.py, bootstrapvz/plugins/docker_daemon/__init__.py, bootstrapvz/providers/oracle/apiclient.py, pylintrc, tox.ini
* pylint import-error bug workaround for distutils
* pylint unidiomatic-typecheck
* pylint len-as-condition
* pylint old-style-class
* add pylintrc and to tox
I disabled some failing tests for now, but at least there will be some test coverage w/ pylint.
=> Add pylint

manifests/README.rst
relates https://github.com/andsens/bootstrap-vz/issues/476
=> add note to manifest docs regarding https repos

bootstrapvz/plugins/pip3_install/README.rst, bootstrapvz/plugins/pip3_install/__init__.py, bootstrapvz/plugins/pip3_install/manifest-schema.yml, bootstrapvz/plugins/pip3_install/tasks.py, bootstrapvz/providers/ec2/ebsvolume.py, bootstrapvz/providers/ec2/tasks/network.py
Copy pasted the `pip_install` command for a `pip3_install`
Additionally:
* Fixed the ENA download URL (Intel broke it with the latest release of the driver. see #402 )
* Increased wait time for the snapshot to get created from 10 minutes to 30 minutes (this was taking around 15-20 minutes today for some reason).
=> Added pip3 plugin
